api/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from tastypie.api import Api

# Urls api
v1_api = Api(api_name='v1')

# importamos clases API

from api.auth import AuthApi
v1_api.register(AuthApi())

# API - Usuarios
from api.api_user import (
    UserApi,
    AdminUpdateApi,
    AdminUpdateCMSApi,
    GroupApi)

v1_api.register(UserApi())
v1_api.register(AdminUpdateApi())
v1_api.register(AdminUpdateCMSApi())
v1_api.register(GroupApi())

# API . Avatar
from api.api_avatar import AvatarApi
v1_api.register(AvatarApi())

# API - Password Usuarios
from api.api_user_password import (
    UserPasswordApi)
v1_api.register(UserPasswordApi())


# API - Contact
from api.api_contact import (
    ContactApi,
    ContactUserApi,
    )

v1_api.register(ContactApi())
v1_api.register(ContactUserApi())

# API - Postulant
from api.api_postulant import (
	PostulantApi,
	PostulantSkillSoftApi,
	PostulantCertificationApi,
	PostulantExperienceApi
	)
v1_api.register(PostulantApi())
v1_api.register(PostulantSkillSoftApi())
v1_api.register(PostulantCertificationApi())
v1_api.register(PostulantExperienceApi())


# API - Skill
from api.api_skill import (
	SkillApi,
	SkillSoftApi
	)
v1_api.register(SkillApi())
v1_api.register(SkillSoftApi())


# API - Level
from api.api_level import (
	LevelApi,
	EvaluationApi)
v1_api.register(LevelApi())
v1_api.register(EvaluationApi())


# API - University
# from api.api_university import (
# 	UniversityApi)
# v1_api.register(UniversityApi())


# API - Weather
from api.api_weather import WeatherApi
v1_api.register(WeatherApi())


urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

users/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
import os
from django.db import models
from users.managers import UserManager
from django.contrib.auth.models import (
    AbstractBaseUser, 
    PermissionsMixin,
    Group
)

def user_image(instance, filename):
    return os.path.join("users/", filename)

class User(AbstractBaseUser, PermissionsMixin):
    rut = models.CharField(
        max_length=15,
        unique=True,
        db_index=True)
    email = models.EmailField(
        verbose_name='Email Address',
        max_length=255,
        db_index=True,
        null=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    contact_phone = models.CharField(max_length=12)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=user_image, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(Group, related_name='user_groups', null=True)


    objects = UserManager()

    USERNAME_FIELD = 'rut'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return unicode(self.email) or u''

    class Meta:
        app_label = 'users'
        db_table = 'users'

users/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.tokens import default_token_generator
from users.models import User
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254)
 
    # removed some parameters that I didn't use
    def save(self, subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             token_generator=default_token_generator,
             from_email=None, html_email_template_name='registration/password_reset_email.html'):
        from django.core.mail import send_mail
        # for some applications I use separate models for Django Admin/Web and API
        # get_api_user_model() returns my ApiUser, use django.contrib.auth.get_user_model()
        # for user model defined in settings.AUTH_USER_MODEL
        UserModel = get_user_model()

        email = self.cleaned_data['email']
        active_users = UserModel._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            # I use application name for both, in the email then I can point the user
            # to the application with an url like: application://passwordreset/secret_code
            # which on IOS and Android should open the app
            site_name = settings.APPLICATION_NAME
            site  = Site.objects.get(pk=settings.SITE_ID)
            protocol = 'https'
            c = {
                'email': user.email,
                'location': 'passwordreset',
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': protocol,
                'domain': site.domain
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
 
            #if html_email_template_name:
            html_email = loader.render_to_string(html_email_template_name, c)
            plain_text_content = loader.render_to_string(email_template_name.replace('with_html', 'plaintext'), c)
            #else:
            #    html_email = None
            #send_mail(subject, email, from_email, [user.email], html_message=html_email)
            from django.core.mail import EmailMultiAlternatives
            msg = EmailMultiAlternatives(subject, plain_text_content, from_email, [user.email])
            msg.attach_alternative(html_email, "text/html")
            msg.send()



class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("rut", "first_name", "last_name", "email", "is_superuser", "password", "contact_phone", "group")

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].label = "Nombre"
        self.fields["last_name"].label = "Apellido"
        self.fields["email"].label = "Email"
        self.fields["contact_phone"].label = "Teléfono"
        self.fields["rut"].label = "Rut"
        self.fields["group"].label = "Perfil Administrador"
        self.fields["rut"].widget.attrs["placeholder"] = "Ingrese sólo números. Si su RUT termina en k, reemplace por un 0."
        self.fields["rut"].widget.attrs["maxlength"] = "9"


class UserFormUpdate(forms.ModelForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "is_superuser", "contact_phone")

    def __init__(self, *args, **kwargs):
        super(UserFormUpdate, self).__init__(*args, **kwargs)
        self.fields["first_name"].label = "Nombre"
        self.fields["last_name"].label = "Apellido"

templates/administrator/add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'admin_list' %}">Administradores</a>
	</li>
	<li>
		<a href="#">Agregar Admin</a>
	</li>
{% endblock %}

{% block page_title %}
	Agregar Nuevo Administrador
{% endblock %}


{% block content %}
	<div class="box">

		<div class="box-body box-padding">
			{% crispy form %}
			<br />
		</div>
		<div class="alert alert-success" id="success_api" style="display:none">
			<i class="fa fa-check"></i>&nbsp;	El administrador fue creado con éxito.
		</div>
		<div class="box-footer">
			<a class="btn btn-danger btn-lg back_report col-sm-12 col-md-12 col-lg-5" style="font-size:16px;padding:16px;" href="{% url 'admin_list' %}"><i class="fa fa-arrow-left" style="margin-right:10px;font-size:18px;"></i>
					Volver a Listado de Administradores
				</a>
			<button class="btn btn-success btn_add col-sm-12 col-md-12 col-lg-6 pull-right" id="btn_add btn-lg" style="font-size:16px;padding:16px"><i class="fa fa-plus" style="margin-right:10px;font-size:18px"></i>Agregar Nuevo Administrador</button>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'app/admin/add.js' %}"></script>
{% endblock %}

templates/administrator/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block breadcrumb %}
	<li>
		<a href="#">Administradores registrados</a>
	</li>
{% endblock %}

{% block page_title %}
	Listado de Administradores TPS-GO
{% endblock %}

{% block content %}
	<div class="box">
		<div class="box-header">
			<a href="{% url 'admin_add' %}" class="btn btn-success pull-right"><i class="fa fa-plus" style="margin-right:10px;font-size:16px"></i>Agregar Administrador</a>
		</div>
        <div class="box-body no-padding">
        <div class="table-responsive">
			<table class="table table-bordered table-striped table-centered" id="admin_table">
				<thead>
					<tr>
						<th>RUT Admin</th>
						<th>Administrador</th>
						<th>Perfil</th>
						<th>Tel. admin</th>
						<th>E-mail</th>
						<th><i class="fa fa-ellipsis-v"></i></th>
					</tr>
				</thead>
				<tbody>
					<!-- Cargar datos -->
				</tbody>
			</table>
		</div>
		</div>
		<div class="container">
	       <div id="page-selection" class="col-sm-10 col-md-10"></div>
	      </div>
		
	</div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'app/jquery.bootpag.min.js' %}"></script>
	<script src="{% static 'app/admin/index.js' %}"></script>
{% endblock %}

templates/administrator/password.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li>
        <a href="{% url 'admin_list' %}">Administradores</a>
    </li>
    <li>
        <a href="#">Editar Admin</a>
    </li>
{% endblock %}

{% block page_title %}
    EDITAR CONTRASEÑA DE ADMINISTRADOR
{% endblock %}

{% block content %}
    <div class="alert alert-success" id="success_api" style="display:none">
        <i class="fa fa-check"></i>&nbsp;   El administrador fue actualizado con éxito.
    </div>
    <div class="box">
        <input type="hidden" id="admin_id" value="{{ admin_id }}">
        <div class="box-body box-padding">
        <form action="" method="PUT" id="admin_form">
            {% csrf_token %}
            <div class="form-group">
                <label for="password" class="control-label">Escriba una contraseña para este administrador</label>
                <div class="controls">
                    <input type="password" name="password" class="textinput textInput form-control" lenght="30" id="password">
                </div>  
            </div>
            <div class="form-group">
                <label for="password_2">Confirme la contraseña</label>
                <div class="controls">
                    <input type="password" name="password_2" class="textinput textInput form-control" lenght="30" id="password_2">
                </div>
            </div>
            <br />
            <div id="message" class="card-panel" style="display:none">
            </div>
        </form>
        </div>
        <div class="box-footer">
            <a class="btn btn-danger btn-lg back_report col-sm-12 col-md-12 col-lg-5" style="font-size:16px;padding:16px;" href="{% url 'admin_list' %}"><i class="fa fa-arrow-left" style="margin-right:10px;font-size:18px;"></i>
                Volver a Listado de Administradores
            </a>
            <button class="btn btn-info btn-lg col-sm-12 col-md-12 col-lg-6 pull-right" style="font-size:16px;padding:16px" id="btn_update"><i class="fa fa-check" style="margin-right:10px;font-size:18px"></i>Editar Contraseña de Administrador</button>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'app/admin/password.js' %}"></script>
{% endblock %}

templates/administrator/update.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'admin_list' %}">Administradores</a>
	</li>
	<li>
		<a href="#">Editar Admin</a>
	</li>
{% endblock %}

{% block page_title %}
	Editar Administrador
{% endblock %}

{% block content %}
	<div class="box">
		<input type="hidden" id="admin_id" value="{{ admin_id }}">
		<div class="box-body box-padding">
		<form action="" method="PUT" id="admin_form">
	        {% csrf_token %}
	        <div class="form-group">
	            <label for="first_name" class="control-label">RUT</label>
	            <div class="controls">
	            	<input type="text" name="rut" class="textinput textInput form-control" lenght="30" id="id_rut">
	            </div>	
	        </div>
	        <div class="form-group">
	            <label for="first_name">Nombre</label>
	            <div class="controls">
	            	<input type="text" name="first_name" class="textinput textInput form-control" lenght="30" id="id_first_name">
	            </div>
	        </div>
	        <div class="form-group">
	            <label for="last_name">Apellidos</label>
	            <div class="controls">
	            	<input type="text" name="last_name" class="textinput textInput form-control" lenght="50" id="id_last_name">
	            </div>
	        </div>
	       <div class="form-group">
	            <label for="last_name">E-mail</label>
	            <div class="controls">
	            	<input type="email" name="email" class="textinput textInput form-control" lenght="50" id="id_email">
	        	</div>
	        </div>
	        <div class="form-group">
	            <label for="last_name">Teléfono</label>
	            <div class="controls">
	            	<input type="text" class="textinput textInput input-custom col-xs-3 col-sm-1" value="+569" disabled="disabled">
	            	<input type="text" name="contact_phone" class="textinput textInput input-custom col-xs-9 col-sm-11" maxlength="8" id="id_contact_phone">
	        	</div>
	        </div>
	        <div class="form-group">
	            <label for="last_name">Perfil Administrador</label>
	            <div class="controls">
	            	<select name="group" id="id_group" class="select form-control"></select>
	        	</div>
	        </div>
	        <br />
	        <div id="admin_medicalcenter_message" class="card-panel" style="display:none">
	            
	        </div>
	    </form>

		</div>
		<div class="alert alert-success" id="success_api" style="display:none">
			<i class="fa fa-check"></i>&nbsp;	El administrador fue actualizado con éxito.
		</div>
		<div class="box-footer">
			<a class="btn btn-danger btn-lg back_report col-sm-12 col-md-12 col-lg-5" style="font-size:16px;padding:16px;" href="{% url 'admin_list' %}"><i class="fa fa-arrow-left" style="margin-right:10px;font-size:18px;"></i>
				Volver a Listado de Administradores
			</a>
			<button class="btn btn-info btn-lg col-sm-12 col-md-12 col-lg-6 pull-right" style="font-size:16px;padding:16px" id="btn_update"><i class="fa fa-check" style="margin-right:10px;font-size:18px"></i>Editar Administrador</button>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'app/admin/update.js' %}"></script>
{% endblock %}