api/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from tastypie.api import Api

# Urls api
v1_api = Api(api_name='v1')

# importamos clases API

from api.auth import AuthApi
v1_api.register(AuthApi())

# API - Usuarios
from api.api_user import (
    UserApi,
    AdminUpdateApi,
    AdminUpdateCMSApi,
    GroupApi)

v1_api.register(UserApi())
v1_api.register(AdminUpdateApi())
v1_api.register(AdminUpdateCMSApi())
v1_api.register(GroupApi())

# API . Avatar
from api.api_avatar import AvatarApi
v1_api.register(AvatarApi())

# API - Password Usuarios
from api.api_user_password import (
    UserPasswordApi)
v1_api.register(UserPasswordApi())


# API - Contact
from api.api_contact import (
    ContactApi,
    ContactUserApi,
    )

v1_api.register(ContactApi())
v1_api.register(ContactUserApi())

# API - Postulant
from api.api_postulant import (
	PostulantApi,
	PostulantSkillSoftApi,
	PostulantCertificationApi,
	PostulantExperienceApi
	)
v1_api.register(PostulantApi())
v1_api.register(PostulantSkillSoftApi())
v1_api.register(PostulantCertificationApi())
v1_api.register(PostulantExperienceApi())


# API - Skill
from api.api_skill import (
	SkillApi,
	SkillSoftApi
	)
v1_api.register(SkillApi())
v1_api.register(SkillSoftApi())


# API - Level
from api.api_level import (
	LevelApi,
	EvaluationApi)
v1_api.register(LevelApi())
v1_api.register(EvaluationApi())


# API - University
# from api.api_university import (
# 	UniversityApi)
# v1_api.register(UniversityApi())


# API - Weather
from api.api_weather import WeatherApi
v1_api.register(WeatherApi())


urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

postulant/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

from postulant.views import (
	PostulantListView,
	PostulantCreateView
	)

urlpatterns = [
	url(r'^$', PostulantListView.as_view(), name='postulant_list'),
	url(r'^add/$', PostulantCreateView.as_view(), name='postulant_add')
 #   	url(r'^(?P<pk>\d+)/update/$', ContactUpdateView.as_view(), name='contact_update'),
]

contact/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from users.models import User

class Contact(models.Model):
    name = models.CharField(max_length=100)
    phones = models.CharField(max_length=200)
    contact_type = models.IntegerField(default=1)
    visible = models.IntegerField(default=1)

    def __unicode__(self):
        return "%s" % self.name

    class Meta:
        app_label = 'contact'
        db_table = 'contact'

class ContactUser(models.Model):
    user = models.ForeignKey(User, null=True)
    contact = models.ForeignKey(Contact, null=True)

    def __unicode__(self):
        return "%s" % self.contact

    class Meta:
        app_label = 'contact'
        db_table = 'contact_user'

postulant/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

import os
from django.db import models
from university.models import University
from skill.models import Skill, SkillSoft
from level.models import Level, Evaluation

class Postulant(models.Model):
	name = models.CharField(max_length=200)
	rut = models.CharField(
        max_length=15,
        unique=True,
        db_index=True)
	birth_date = models.DateField(null=True)
	email = models.EmailField(
        max_length=255,
        db_index=True,
        null=True)
	visible = models.IntegerField(default=1)
	evaluation = models.ForeignKey(Evaluation, null=True)
	university = models.ForeignKey(University, null=True)
	skills = models.ManyToManyField(Skill)
	level = models.ForeignKey(Level, null=True)
	interview_date = models.DateField(null=True)
	income_claim = models.IntegerField(null=True)

	def __unicode__(self):
		return "%s" % self.name

	class Meta:
		app_label = 'postulant'
		db_table = 'postulant'


class PostulantSkillSoft(models.Model):
	postulant = models.ForeignKey(Postulant, null=True)
	skill_soft = models.ForeignKey(SkillSoft, null=True)
	score = models.IntegerField(default=0)

	def __unicode__(self):
		return "%s" % self.postulant.name

	class Meta:
		app_label = 'postulant'
		db_table = 'postulant_skill_soft'


class PostulantCertification(models.Model):
	postulant = models.ForeignKey(Postulant, null=True)
	certification_name = models.CharField(max_length=200)
	year = models.DateField(null=True)
	institution = models.CharField(max_length=200)

	def __unicode__(self):
		return "%s" % self.postulant.name

	class Meta:
		app_label = 'postulant'
		db_table = 'postulant_certification'


class PostulantExperience(models.Model):
	postulant = models.ForeignKey(Postulant, null=True)
	year_from = models.DateField(null=True)
	year_to = models.DateField(null=True)
	work_position = models.CharField(max_length=200)
	organitation = models.DateField(max_length=200, null=True)

	def __unicode__(self):
		return "%s" % self.postulant.name

	class Meta:
		app_label = 'postulant'
		db_table = 'postulant_experience'

postulant/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.core.validators import URLValidator, RegexValidator

from crispy_forms.helper import FormHelper

from postulant.models import (
	Postulant
	)


class PostulantForm(forms.ModelForm):

	class Meta:
		model = Postulant
		fields = ('name', 'rut', 'birth_date', 'email', 'evaluation', 'university', 'skills', 'level', 'interview_date')

	def __init__(self, *args, **kwargs):
		super(PostulantForm, self).__init__(*args, **kwargs)
		self.fields["name"].label = "Postulant Full Name"
		self.fields["rut"].label = "RUT"
		self.fields['birth_date'].label = "Birth Date"
		self.fields['email'].label = "Email"
		self.fields['evaluation'].label = "Evaluation"
		self.fields['university'].label = "University"
		self.fields['skills'].label = "Technical Skills"
		self.fields['level'].label = "Level for which she/he postulates"
		self.fields['interview_date'].label = "Interview Date"

		self.helper = FormHelper()
		self.helper.form_id = 'postulant_form'

postulant/views.py
from django.shortcuts import render

from django.views.generic import (
	TemplateView,
	FormView)

from postulant.forms import PostulantForm

from braces.views import LoginRequiredMixin

class PostulantListView(LoginRequiredMixin, TemplateView):
	template_name = 'postulant/index.html'
	login_url = '/'

class PostulantCreateView(LoginRequiredMixin, FormView):
	template_name = 'postulant/add.html'
	login_url = '/'
	form_class = PostulantForm

templates/postulant/add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
	<li>
		<a href="{% url 'postulant_list' %}">Applicant</a>
	</li>
	<li>
		<a href="#">Add Applicant</a>
	</li>
{% endblock %}

{% block page_title %}
	Add Applicant
{% endblock %}

{% block content %}
	<div class="row" style="padding:12px 0px;background-color:white;">
		
		<div class="col-sm-12 col-md-12 col-lg-10">
			<div class="box">
				<div class="box-body box-padding" style="background-color:rgb(249, 249, 249);">
					{% crispy form %}
				</div>
				
			</div>
		</div>
	
		<div class="col-sm-12 col-md-12 col-lg-12">
			<div class="alert alert-success" id="success_contact" style="display:none">
				<i class="fa fa-check"></i>&nbsp;The applicant was saved successfully.
			</div>
		</div>

		<div class="col-sm-12 col-md-12 col-lg-12 box-footer" style="margin-top:30px">
			<a class="btn btn-danger btn-lg back_report col-sm-12 col-md-12 col-lg-5" id="btn_update" style="font-size:16px;padding:16px;" href="{% url 'contact_list' %}"><i class="fa fa-arrow-left" style="margin-right:10px;font-size:18px;"></i>
				Back to list
			</a>

			<button class="btn btn-success btn-lg pull-right col-sm-12 col-md-12 col-lg-6" id="btn_add" style="font-size:16px;padding:16px;"><i class="fa fa-plus" style="margin-right:10px;font-size:18px"></i>Save Applicant</button>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'app/postulant/add.js' %}"></script>
{% endblock %}

templates/postulant/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block breadcrumb %}
	<li>
		<a href="#">Postulants</a>
	</li>
{% endblock %}

{% block page_title %}
	Postulants
{% endblock %}

{% block content %}
	<!-- Modal box para eliminar protocolo -->
	<div class="modal fade" id="deleteMessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Delete Postulant</h4>
				</div>
				
				<div class="modal-body">
				<div id="_protocol"></div>
				Are you sure to delete the selected applicant?
				{% csrf_token %}
				</div>

				<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
				<a type="button" href="#" class="btn btn-success" data-dismiss="modal" data-uri="" id="btn_confirm_delete">Yes, I'm sure.</a>
				</div>
			</div>
		</div>
    </div>
	<!-- Fin modal box -->

	<div class="box">
		<div class="box-header">
			<a href="{% url 'postulant_add' %}" class="btn btn-success pull-right"><i class="fa fa-plus" style="margin-right:10px;font-size:16px"></i>Add Postulant</a>
		</div>
        <div class="box-body no-padding table-responsive">
			<table class="table table-bordered table-striped table-centered" id="message_table">
				<thead>
					<tr>
						<th style="min-width:300px">Postulant Name</th>
						<th>Level</th>
						<th>Age</th>
						<th>Evaluation</th>
						<th>Email</th>
						<th>Interview Date</th>
						<th style="min-width:80px"><i class="fa fa-ellipsis-v"></i></th>
					</tr>
				</thead>
				<tbody>
					<!-- Cargar datos -->
				</tbody>
			</table>
		</div>
		<div class="container">
	       <div id="page-selection" class="col-sm-10 col-md-10"></div>
	      </div>
		
	</div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'app/jquery.bootpag.min.js' %}"></script>
	<script src="{% static 'app/postulant/index.js' %}"></script>
{% endblock %}